server:
  port: 7050

spring:
  application:
    name: mybatis-plus
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://172.16.0.10:33066/pregrisk_test?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis-plus:
  type-aliases-package: cn.sanske.mybatisplus.mapper
  mapper-locations: classpath:/mapper/*.xml